### ISSUE TITLE
How to detect invalid country code?

### ISSUE THREAD

**Issue by lavanya051992** [cvzi/flag#48]
The flags work fine when I have a valid country code. If I create a dummy country Code which doesn't exist then how do I detect that?
If I do flag.flag(countrycode) it gets converted to two letter code irrespective of If it's valid or not.
But I don't want to display this two letter code in my UI. Just want to display the emoji if available

**Comment by cvzi** [comment]
You can check if the code is a valid [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) country code with other packages, for example https://pypi.org/project/pycountry/ can do that.


However I am not aware of a way to check if the emoji is actually available or if the two letter code is displayed.

[emojipedia.org](https://emojipedia.org/) has tables of all supported emoji for the major apps/devices.
For example: https://emojipedia.org/whatsapp or https://emojipedia.org/microsoft
These tables could be parsed to have a list of supported countries for each app/device, but I am not planing to add this to the package.

Another way could be: render the emoji as text and then check the width or inspect the pixel colors to find out whether the emoji is displayed or whether the letters are displayed.

**Comment by cvzi** [comment]
I have added support for this, because recently the support of flag has been similar across different devices (mainly Android and iPhones now support the same flags). 
Each supported flag is hardcoded in https://github.com/cvzi/flag/blob/main/flag/data/__init__.py
I plan to check the support regularly.

Among [other functions](https://flag.readthedocs.io/en/latest/#flag.flag_safe), you can now choose to only convert supported flags:

```python
flag.Flag(only_supported=True).flagize("Convert supported flags like :US: but not things like :XX:")
>>> "Convert supported flags like 🇺🇸 but not things like :XX:"

```
