### ISSUE TITLE
Black flag detection

### ISSUE THREAD

**Issue by ohld** [cvzi/flag#6]
I have 3-letter country codes that I'd like to convert to emoji. The list looks lie this:
```
IND, NGA, KEN, ITA, USA, CUB, ZAF, GBR, POL, GHA, MAR, IDN, ESP, BRA, FRA
```

I understand that emoji uses two-letter country codes so I cut 3-letters to 2-letters (in most cases it works). But I faced the "black flag" problem.

If I try to get emoji from unknown 2 symbols, the library may return a black flag. How can I detect that?

Moreover there are a lot of symbols that looks like "black flag" so I can't use a simple `==` operator.

![image](https://user-images.githubusercontent.com/5613295/86362480-0391a800-bc7e-11ea-984e-196db87492c7.png)

**Comment by cvzi** [comment]
Detecting unknown flags is difficult. Therefore this library just "translates" the letter code into emoji, it doesn't do any checks.
The problem is that not every device supports the same flags. When you see a black flag in your terminal, it may actually display as a correct flag on a mobile phone. 

The black flag is not an error, it just means your device cannot display the flag.

------

Could you give an example when you see a black flag with a 2 symbol code? I actually believe the black flags should never occur if you use 2 symbols. Instead it should just spell the symbols:
```
Correct 2-letter code:       flag.flag("PL")  =>    🇵🇱      (This should show Polish flag on supported devices)
Incorrect 2-letter code:     flag.flag("PO")  =>    🇵🇴      (This should always spell PO and not show a black flag)
Incorrect 3-letter code:     flag.flag("POL") =>    🏴󠁰󠁯󠁬󠁿      (This should always be a black flag)
```
------
The problem remains that `PO` are not the correct symbols, but `PL` is correct.

But you can make sure that you get the correct 2-letter codes.
The correct ones are listed here: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements.

I suggest you use some sort of a table to look up the correct 2-letter code for your 3-letter codes. For example this package https://pypi.org/project/pycountry/ can do it for you:

```python
import flag
import pycountry

testlist = ["IND", "NGA", "KEN", "ITA", "USA", "CUB", "ZAF", "GBR", "POL", "GHA", "MAR", "IDN", "ESP", "BRA", "FRA", "XYZ"]

for threeletter in testlist:
    country = pycountry.countries.get(alpha_3=threeletter)
    if country is not None:
        twoletter = country.alpha_2 
        print(threeletter + " = " + flag.flag(twoletter)) 
    else:
        print("invalid code: " + threeletter) 

```
This will make it better, but not perfect. Even on newest phones not all of these **ISO 3166-1 alpha-2** codes are supported. And on older Android versions only a few are supported.

**Comment by ohld** [comment]
Thanks for your answer! 

If the end I just came up with a simple dict from the 3-letter countries I have to emoji they represent. And I will just add more countries manually when I will have more users from even more countries. 

I can share this dict with you, maybe it will be awesome to add it to the library. Who knows.

**Comment by cvzi** [comment]
I think I will just add an explanation in the Readme.
Is your project public/on github?

**Comment by ohld** [comment]
@cvzi No, this is internal project and I just wanted to show the emojis for users instead of text. Right now I'm not using your library - I just created a dictionary.

**Comment by ohld** [comment]
Just published my gist with dictionary. May be useful: https://gist.github.com/ohld/6f42d1ed4a05ec084f172b86775c09bf
